use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::PathBuf;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AppConfig {
    pub default_speaker: String,
    pub default_speed: f32,
    pub device: String,
    pub sample_rate: u32,
    pub volume_gain: f32,
    pub pitch_shift: f32,
    pub length_scale: f32,
    pub noise_scale: f32,
    pub output_format: String,
    pub cache_enabled: bool,
    pub custom_model_dir: Option<String>,
}

impl Default for AppConfig {
    fn default() -> Self {
        Self {
            default_speaker: "en_1.5b_speaker_0".to_string(),
            default_speed: 1.0,
            device: "auto".to_string(),
            sample_rate: 22050,
            volume_gain: 1.0,
            pitch_shift: 1.0,
            length_scale: 1.0,
            noise_scale: 0.667,
            output_format: "wav".to_string(),
            cache_enabled: true,
            custom_model_dir: None,
        }
    }
}

pub struct Paths;

impl Paths {
    /// Directory containing the currently running executable.
    pub fn binary_dir() -> Result<PathBuf> {
        let exe = std::env::current_exe().context("Failed to get current executable path")?;
        let dir = exe
            .parent()
            .context("Failed to get binary directory")?
            .to_path_buf();
        Ok(dir)
    }

    /// Current working directory (where output files are generated by default).
    pub fn working_dir() -> Result<PathBuf> {
        let cwd = std::env::current_dir().context("Failed to get current working directory")?;
        Ok(cwd)
    }

    /// Path to models directory strictly inside binary's dir.
    pub fn models_dir() -> Result<PathBuf> {
        Ok(Self::binary_dir()?.join("models"))
    }

    /// Path to cache directory strictly inside binary's dir.
    pub fn cache_dir() -> Result<PathBuf> {
        Ok(Self::binary_dir()?.join("cache"))
    }

    /// Path to default output WAV file inside current working directory.
    pub fn default_output() -> Result<PathBuf> {
        Ok(Self::working_dir()?.join("output.wav"))
    }

    /// Path to configuration JSON file inside binary's dir.
    pub fn config_file() -> Result<PathBuf> {
        Ok(Self::binary_dir()?.join("config.json"))
    }

    /// Ensures required asset folders in the binary dir exist and sets process env.
    pub fn init_environment() -> Result<()> {
        let models = Self::models_dir()?;
        let cache = Self::cache_dir()?;

        fs::create_dir_all(&models).context("Failed to create local models directory")?;
        fs::create_dir_all(&cache).context("Failed to create local cache directory")?;

        std::env::set_var("HF_HOME", &cache);
        std::env::set_var("XDG_CACHE_HOME", &cache);
        std::env::set_var("TRANSFORMERS_CACHE", &cache);
        std::env::set_var("TORCH_HOME", &cache);

        Ok(())
    }

    /// Deletes all downloaded models, cache, and temporary data inside binary directory.
    pub fn clean_all() -> Result<(u64, usize)> {
        let models = Self::models_dir()?;
        let cache = Self::cache_dir()?;
        let config = Self::config_file()?;

        let mut deleted_bytes = 0u64;
        let mut deleted_count = 0;

        if models.exists() {
            let (b, c) = Self::dir_size(&models)?;
            deleted_bytes += b;
            deleted_count += c;
            let _ = fs::remove_dir_all(&models);
        }

        if cache.exists() {
            let (b, c) = Self::dir_size(&cache)?;
            deleted_bytes += b;
            deleted_count += c;
            let _ = fs::remove_dir_all(&cache);
        }

        if config.exists() {
            if let Ok(meta) = config.metadata() {
                deleted_bytes += meta.len();
                deleted_count += 1;
            }
            let _ = fs::remove_file(&config);
        }

        Ok((deleted_bytes, deleted_count))
    }

    fn dir_size(path: &PathBuf) -> Result<(u64, usize)> {
        let mut size = 0u64;
        let mut count = 0;
        if let Ok(entries) = fs::read_dir(path) {
            for entry in entries.flatten() {
                let p = entry.path();
                if p.is_dir() {
                    let (sub_size, sub_count) = Self::dir_size(&p)?;
                    size += sub_size;
                    count += sub_count;
                } else if let Ok(meta) = p.metadata() {
                    size += meta.len();
                    count += 1;
                }
            }
        }
        Ok((size, count))
    }

    /// Loads app configuration from <binary_dir>/config.json or creates default.
    pub fn load_or_create_config() -> Result<AppConfig> {
        let cfg_path = Self::config_file()?;
        if cfg_path.exists() {
            let content = fs::read_to_string(&cfg_path).context("Failed to read config.json")?;
            let cfg: AppConfig = serde_json::from_str(&content).unwrap_or_default();
            Ok(cfg)
        } else {
            let default_cfg = AppConfig::default();
            let content = serde_json::to_string_pretty(&default_cfg)?;
            let _ = fs::write(&cfg_path, content);
            Ok(default_cfg)
        }
    }
}
